version: '3.8'

services:
  my-app:
    container_name: movie-app-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    ports:
      - '4002:80' # <--- CHANGED THIS PORT