# docker-compose.yml

version: '3.8'

services:
  my-app:
    container_name: movie-app-container
    build:
      context: .
      dockerfile: Dockerfile
      # Pass the API key from your .env file to the Dockerfile
      args:
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    ports:
      - '3000:80'